# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nastroika.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow3):
        MainWindow3.setObjectName("MainWindow3")
        MainWindow3.resize(372, 139)
        MainWindow3.setMinimumSize(QtCore.QSize(372, 139))
        MainWindow3.setMaximumSize(QtCore.QSize(372, 139))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("иконка.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow3.setWindowIcon(icon)
        MainWindow3.setStyleSheet("font: 12pt \"Comic Sans MS\";\n"
"background-color: rgb(207, 212, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("настройка.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 20, 211, 31))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(130, 70, 211, 21))
        self.radioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton.setObjectName("radioButton")
        MainWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow3.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow3)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow3)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow3)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow3)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow3)

    def retranslateUi(self, MainWindow3):
        _translate = QtCore.QCoreApplication.translate
        MainWindow3.setWindowTitle(_translate("MainWindow3", "Настройки"))
        self.pushButton.setText(_translate("MainWindow3", "Сменить тему"))
        self.radioButton.setText(_translate("MainWindow3", "Сбросить все"))
        self.menu.setTitle(_translate("MainWindow3", "Меню"))
        self.action.setText(_translate("MainWindow3", "Главное окно"))
        self.action_2.setText(_translate("MainWindow3", "Справка"))
        self.action_3.setText(_translate("MainWindow3", "Помощь"))
        self.action_4.setText(_translate("MainWindow3", "Выход"))
