# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'podscazka.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(353, 236)
        MainWindow2.setMinimumSize(QtCore.QSize(353, 236))
        MainWindow2.setMaximumSize(QtCore.QSize(353, 236))
        MainWindow2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("иконка.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow2.setWindowIcon(icon)
        MainWindow2.setStyleSheet("font: 12pt \"Comic Sans MS\";\n"
"background-color: rgb(207, 212, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 170, 331, 31))
        self.lineEdit.setStyleSheet("font: 12pt \"Comic Sans MS\";")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 0, 141, 171))
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(240, 240))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow2.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow2)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow2)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow2)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow2)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "Подсказка"))
        self.menu.setTitle(_translate("MainWindow2", "Меню"))
        self.action.setText(_translate("MainWindow2", "Погода"))
        self.action_2.setText(_translate("MainWindow2", "Справка"))
        self.action_3.setText(_translate("MainWindow2", "Помощь"))
        self.action_4.setText(_translate("MainWindow2", "Выход"))
